"""Replay the whole demo dataset in parallel and cache (obs, action) pairs.

The dataset stores only actions, so observations must be regenerated by
replaying each episode in the deterministic env.  Single-core that is ~4.3 h
for all 34,777 episodes; this splits the episodes across processes, so a
384-core CPU node does it in minutes.

    python scripts/il/build_replay_cache.py --workers 64 --out storage_local/cache/replay_full.npz
"""
from __future__ import annotations

import argparse
import sys
import time
from multiprocessing import Pool
from pathlib import Path

import numpy as np
from gymnasium.spaces.utils import flatten
from loguru import logger

PROJECT_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(PROJECT_ROOT))
from ant_swarm import AntSwarmEnv, load_config     # noqa: E402

_G = {}


def _init(config, dataset):
    cfg = load_config(config).copy()
    cfg.env.reward_mode = "sparse"
    _G["env"] = AntSwarmEnv(config=cfg, seed=0)
    z = np.load(dataset)
    _G.update(offsets=z["offsets"], actions=z["actions"], init_pose=z["init_pose"],
              goal=z["goal"], route=z["route"])


def _run(span):
    lo, hi = span
    env = _G["env"]
    offsets, actions_flat = _G["offsets"], _G["actions"]
    tip_local, heads = env.obs_model.tip_local, env.layout.wall_heads
    obs_l, act_l, sgn_l, rt_l, ep_l, cx_l = [], [], [], [], [], []

    for i in range(lo, hi):
        acts = actions_flat[offsets[i]:offsets[i + 1]]
        center = np.asarray(_G["init_pose"][i][:2], dtype=np.float32)
        angle = float(_G["init_pose"][i][2])
        if not env._pose_is_free(center, angle):
            continue
        env.reset(seed=i, options={"init_pose": _G["init_pose"][i],
                                   "goal": _G["goal"][i]})

        for raw in acts:
            obj = env.state.obj
            obs_l.append(flatten(env.observation_space,
                                 env.obs_model.observe(env.state)).astype(np.float32))
            tips = obj.center[None, :] + tip_local @ obj.rot().T
            sgn_l.append((tips[:, None, :] - heads[None, :, :]).reshape(-1).astype(np.float32))
            act_l.append(np.asarray(raw, dtype=np.float32).ravel())
            rt_l.append(_G["route"][i])
            ep_l.append(i)
            cx_l.append(float(obj.center[0]))
            _, _, term, trunc, _ = env.step(
                np.asarray(raw, dtype=np.float32).reshape(env.action_space.shape))
            if term or trunc:
                break

    return (np.asarray(obs_l, dtype=np.float32), np.asarray(act_l, dtype=np.float32),
            np.asarray(sgn_l, dtype=np.float32), np.asarray(rt_l, dtype=np.float32),
            np.asarray(ep_l, dtype=np.int64), np.asarray(cx_l, dtype=np.float32))


def main():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--config", default="configs/il/il_augmented_bc.yaml")
    p.add_argument("--dataset", default="storage_local/datasets/successes_v1/dataset.npz")
    p.add_argument("--out", default="storage_local/cache/replay_full.npz")
    p.add_argument("--episodes", type=int, default=0, help="0 = all")
    p.add_argument("--workers", type=int, default=32)
    args = p.parse_args()

    total = len(np.load(args.dataset)["offsets"]) - 1
    n = total if args.episodes <= 0 else min(total, args.episodes)
    spans = [(a, min(a + 200, n)) for a in range(0, n, 200)]
    logger.info(f"replaying {n} episodes in {len(spans)} spans on {args.workers} workers")

    t0 = time.time()
    parts = []
    with Pool(args.workers, initializer=_init, initargs=(args.config, args.dataset)) as pool:
        for k, part in enumerate(pool.imap(_run, spans), 1):
            parts.append(part)
            if k % 20 == 0 or k == len(spans):
                logger.info(f"  {k}/{len(spans)} spans, {time.time()-t0:.0f}s")

    keys = ["obs", "act", "signed", "route", "epid", "cx"]
    data = {k: np.concatenate([p[j] for p in parts if len(p[j])], axis=0)
            for j, k in enumerate(keys)}
    data["goal_observation_version"] = np.array(2, dtype=np.int32)
    data["route"] = data["route"].reshape(-1, 1)
    env = AntSwarmEnv(config=load_config(args.config), seed=0)
    data["tip_local"] = env.obs_model.tip_local
    data["heads"] = env.layout.wall_heads
    env.close()

    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    np.savez(out, **data)          # uncompressed: much faster to write and read
    logger.info(f"{len(data['obs'])} transitions -> {out} ({time.time()-t0:.0f}s)")


if __name__ == "__main__":
    main()
